#hexo new page 
menu:
  主页: https://jerryz.com.cn/ || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  留言板: /messageboard/ || fas fa-comments
  # 说说: /shuoshuo/ || fas fa-comment-dots
  友链|| fas fa-link:
      Links: https://links.jerryz.com.cn/go/ || iconfont icon-Links
      开往: https://www.travellings.cn/go.html || fas fa-train-subway
      # 虫洞: http://foreverblog.cn/go.html || far fa-circle
  # 关于: /article/about/ || fas fa-heart
  支持: https://pay.jerryz.com.cn/ || fas fa-heart
  # 更多||fa fa-list:
  #   GitHub: https://github.com/YangguangZhou || fab fa-github
  #   音乐: /music/ || fas fa-music
  #   照片: /Gallery/ || fas fa-images
  #   电影: /movies/ || fas fa-video

# Image (圖片設置)
# --------------------------------------

# Favicon（網站圖標）
favicon: https://img.examcoo.com/ask/7386438/202112/163854209919410.png

# The banner image of archive page
archive_img: https://img.examcoo.com/ask/7386438/202111/163673216190400.jpg
tag_img: https://img.examcoo.com/ask/7386438/202111/163673216190400.jpg
category_img: https://img.examcoo.com/ask/7386438/202111/163673216190400.jpg
about_img: https://img.examcoo.com/ask/7386438/202111/163673216190400.jpg

inject:
  # css
  head:
    # 图标
    - <link rel="stylesheet" href="https://at.alicdn.com/t/c/font_2954574_1ck6xsanalb.css">
    # Links
    # - <link rel="stylesheet" href="https://at.alicdn.com/t/c/font_3891026_wggdqlhqrxg.css">
    - <link rel="stylesheet" href="/css/mycss.css">
    - <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2597042766299857" crossorigin="anonymous"></script>
    - <link rel="stylesheet" href="https://unpkg.com/heti/umd/heti.min.css">
    - <link rel="stylesheet" href="https://unpkg.com/@waline/client@2.15.0/dist/waline-meta.css" />
    - <script async src="https://umami.jerryz.com.cn/script.js" data-website-id="a219fdba-6ff8-4e89-b50a-56124d4fc5fa"></script>
    # - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/StylishThemes/GitHub-Dark@master/github-dark.user.css">
  # javascript
  bottom:
  # - <script src="https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@latest/Hexo/js/hideMobileSidebar.js"></script>

cover:
  # display the cover or not (是否显示文章封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面显示的位置)
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed (当没有设置cover时，默认的封面显示)
  default_cover:
    https://img.examcoo.com/ask/7386438/202111/163673216190400.jpg

# Avatar (頭像)
avatar:
  img: https://img.examcoo.com/ask/7386438/202111/163626915705190.jpg
  effect: false

# the banner image of home page

subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (循環打字)
  loop: true
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  # 如果有英文逗號' , ',請使用轉義字元 &#44;
  # 如果有英文雙引號' " ',請使用轉義字元 &quot;
  # 開頭不允許轉義字元，如需要，請把整個句子用雙引號包住
  # 如果關閉打字效果，subtitle只會顯示sub的第一行文字
  sub: 
    - 永远相信美好的事情即将发生
  # source調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  source: 3

social:
  iconfont icon-github: https://github.com/YangguangZhou || Github
  iconfont icon-luogu: https://www.luogu.com.cn/user/253620 ||Luogu
  iconfont icon-bilibili: https://space.bilibili.com/489004177 || bilibili
  iconfont icon-email: https://img.shields.io/badge/%E9%82%AE%E7%AE%B1-yangguangzhousunny%40163.com-279cff || Email
  iconfont icon-weixin: https://img.shields.io/badge/%E5%BE%AE%E4%BF%A1-ilovegithub-279cff || 微信
  iconfont icon-QQ: https://img.shields.io/badge/QQ-2098412009-279cff || QQ

katex:
  enable: true
  # true 表示每一页都加载katex.js
  # false 需要时加载，须在使用的Markdown Front-matter 加上 katex: true
  per_page: true
  hide_scrollbar: true

# the banner image of home page
index_img: https://img.examcoo.com/ask/7386438/202111/163673216190400.jpg

# # electric_clock
# electric_clock:
#   enable: true # 开关
#   priority: 5 #过滤器优先权
#   enable_page: all # 应用页面
#   exclude:
#     # - /posts/
#     # - /about/
#   layout: # 挂载容器类型
#     type: class
#     name: sticky_layout
#     index: 0

# Code Blocks (代碼相關)
# --------------------------------------  //代码高亮配置 我喜欢mac light样式，可以自行选择

highlight_theme: mac # default / darker / pale night / light / ocean / mac / false
#highlight_theme: false
highlight_copy: true # copy button
highlight_lang: true # show the code language

error_404:
  enable: true
  subtitle: 'Page Not Found'
  background: https://img.examcoo.com/ask/7386438/202111/163673216190400.jpg

post_meta:
  page:
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: created # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "很抱歉，暂无${query}相关的内容" # if there are no result

# toc (目錄)
toc:
  enable: true
  number: true
  auto_open: true # auto open the sidebar
  priority: 3

# Related Articles
related_post:
  enable: true
  limit: 6 # Number of posts displayed  显示的文章数
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

# Sponsor/reward打赏
reward:
  enable: true
  QR_code:
    - img: https://pay.jerryz.com.cn/qrcode.png
      link: https://pay.jerryz.com.cn/sponsor
      text: 万能收款码
    - img: https://img.examcoo.com/ask/7386438/202112/163940919901510.png
      link:
      text: 微信
    - img: https://img.examcoo.com/ask/7386438/202112/163940919311760.jpg
      link:
      text: 支付宝

# aside (側邊欄)
# --------------------------------------
aside:
  enable: true
  mobile: true # display on mobile
  position: right # left or right 
  # 公告栏
  card_announcement:
      enable: true
      content: 永远相信美好的事情即将发生  #修改此处
  card_author:
    enable: true
    description: 永远相信美好的事情即将发生
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/YangguangZhou
  card_recent_post:
    enable: true
    limit: 5
    sort: date
  card_hitokoto: 
    enable: true
  card_tags:
    enable: true
    limit: 0 # if set 0 will show all
    color: true

# Aside widget - Newest Comments
newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 3 # unit: mins, save data to localStorage
  avatar: true

# 訪問人數
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
  
# 網頁運行時間
runtimeshow:
  enable: true
  publish_date: 2021/11/27 22:15:23
  #格式: 月/日/年 時間
  #也可以 年/月/日 時間

# # Typewriter Effect (打字效果)
# # https://github.com/disjukr/activate-power-mode
# activate_power_mode:
#   enable: true
#   colorful: true # open particle animation (冒光特效)
#   shake: false #  open shake (抖動特效)
#   mobile: true

# Snackbar (Toast Notification 彈窗)
# https://github.com/polonel/SnackBar
# position 彈窗位置
# 可選 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: top-right  #弹窗位置
  bg_light: '#49b1f5' # The background color of Toast Notification in light mode
  bg_dark: '#121212' # The background color of Toast Notification in dark mode

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# dark mode
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: 1

translate:
  enable: true
  # 默认按钮显示文字(网站是简体，应设置为'default: 繁')
  default: 繁
  #网站默认语言，1: 繁体中文, 2: 简体中文
  defaultEncoding: 2
  #延迟时间,若不在前, 要设定延迟翻译时间, 如100表示100ms,默认为0
  translateDelay: 0
  #博客网址
  cookieDomain: "https://blog.jerryz.com.cn/"
  #当文字是简体时，按钮显示的文字
  msgToTraditionalChinese: "繁"
  #当文字是繁体时，按钮显示的文字
  msgToSimplifiedChinese: "简"

note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

theme_color:
  enable: true
  main: "#279cff"
  paginator: "#279cff"
  button_hover: "#FF7242"
  text_selection: "#279cff"
  link_color: "#0e83cd"
  hr_color: "#A4D8FA"
  toc_color: "#279cff"

canvas_fluttering_ribbon:
  enable: true
  mobile: true # false 手机端不显示 true 手机端显示

# 美化页面显示
beautify:
  enable: true
  field: site

# # Global font settings
# # Don't modify the following settings unless you know how they work (非必要不要修改)
# font:
#   global-font-size:
#   code-font-size:
#   font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "Microsoft JhengHei", "Microsoft YaHei", sans-serif
#   code-font-family: consolas, Menlo, "Microsoft JhengHei", "Microsoft YaHei", sans-serif

# 加载动画 Loading Animation
preloader: true

# fancybox http://fancyapps.com/fancybox/3/
fancybox: true

# https://instant.page/
# prefetch (预加载)
instantpage: true

# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax: 
  enable: true

index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: Waline
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: true # Display comment count in top_img
  card_post_count: ture # Display comment count in Home Page

baidu_analytics: 2d0f2589d6d85efeff9dcfd00a508157

# waline - A simple comment system with backend support fork from Valine
# https://waline.js.org/
waline:
  serverURL:  https://waline.jerryz.com.cn/ # Waline server address url
  # bg: https://cdn.jsdelivr.net/gh/YangguangZhou/jzblog-waline@main/comment.webp # waline background
  pageview: false
  option:

footer:
  owner:
    enable: true
    since: 2021

# footer是否显示图片背景(与top_img一致)
footer_bg: true

# copy settings
# copyright: Add the copyright information after copied content (复製的内容后面加上版权信息)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 60

post_copyright:
  enable: true
  decode: true
  author_href: https://blog.jerryz.com.cn/
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# anchor
# when you scroll in post , the url will update according to header id.
anchor: true

sharejs:
  enable: true
  sites: facebook,twitter,weibo,wechat,qq

# Chat Button [recommend]
# It will create a button in the bottom right corner of website, and hide the origin button
# chat_btn: true

# tidio
# https://www.tidio.com/
# tidio:
#   enable: false
#   public_key: fodbfserjbldd3xxm0uvbh6nltjp4i80

# post_pagination (分页)
# value: 1 || 2 || false
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: 2

index_post_content:
  method: 2
  length: 500 # if you set method to 2 or 3, the length need to config

google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-2597042766299857 # 填入个人识别码
  enable_page_level_ads: true

# HexoPlusPlus Talk
# see https://hexoplusplus.js.org
hpptalk:
  enable: true 
  domain: hpp.jerryz.com.cn
  path: hpptalk
  limit: 8
  start: 0
  js: https://cdn.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@latest/talk_user.js
  css: https://cdn.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@latest/talk.css