name: Update Stars File

on:
  schedule:
    - cron: '0 1 * * 1' # Runs at 01:00 UTC on Mondays, which is 09:00 Beijing time
  workflow_dispatch: # Allows for manual triggering

jobs:
  update-stars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download README.md
      run: curl -o temp.md https://raw.githubusercontent.com/YangguangZhou/some-stars/main/README.md

    - name: Add header to the file
      run: |
        TZ=Asia/Shanghai
        echo "---" > stars.md
        echo "title: Some Stars - 我的 Star 列表" >> stars.md
        echo "date: 2024/06/18 22:29:28" >> stars.md
        echo "description: Jerry Zhou的star列表，每周自动更新" >> stars.md
        echo "categories:" >> stars.md
        echo "- 编程" >> stars.md
        echo "tags:" >> stars.md
        echo "- 编程" >> stars.md
        echo "- GitHub" >> stars.md
        echo "keywords: 编程,GitHub,Stars,项目" >> stars.md
        echo "abbrlink: 9569" >> stars.md
        echo "cover: https://img.examcoo.com/ask/7386438/202406/171872023848900.png" >> stars.md
        echo "main_color: '#271f5c'" >> stars.md
        echo "ai: 这篇文章介绍了Jerry Zhou的GitHub star列表，涵盖了多个编程语言和工具的开源项目。主要类别包括Vue、Kotlin、Dart、JavaScript、Python、TypeScript、Go、Shell、Rust、Svelte、HTML、Stylus、Batchfile、Java、杂项、PHP以及Jupyter Notebook。每个类别下列出了相关的项目及其简短描述。" >> stars.md
        echo "updated: $(date +'%Y/%m/%d %H:%M:%S')" >> stars.md
        echo "---" >> stars.md
        cat temp.md >> stars.md

    - name: Move file to the target directory
      run: mv stars.md source/_posts/stars.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add source/_posts/stars.md
        git commit -m 'Update stars.md file'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
